name: Project Android

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-20.04
    
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2.3.4

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Unit tests
        id: tests
        run: ./gradlew test

      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew bundleRelease
  
      - name: Upload AAB
        id: uploadArtifact
        uses: actions/upload-artifact@v1
        with:
            name: app
            path: app/build/outputs/bundle/release/app-release.aab
          
          
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      
      - name: Sign app Android release custom
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          
      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT_JSON}}
          packageName: com.kotlinquiz.app
          releaseFile: app/build/outputs/bundle/release/app-release.aab
          track: beta

    
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
        
