name: Project Android

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2.3.4

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Unit tests
        id: tests
        run: ./gradlew test

      - name: Upload APK
        uses: actions/upload-artifact@v2.2.1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      
      - name: Upload AAB
        uses: actions/upload-artifact@v2.2.1
        with:
          name: app
          path: app/build/outputs/bundle/release/app-release.aab
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
        
