name: Project Android

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2.3.4

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Unit tests
        id: tests
        run: ./gradlew test

      - name: Upload APK
        uses: actions/upload-artifact@v2.2.1
        with:
          name: app
          path: app/build/outputs/apk/release/app-debug.apk

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      
      - name: Upload AAB
        uses: actions/upload-artifact@v2.2.1
        with:
          name: app
          path: app/build/outputs/bundle/release/app-release.aab
      
      - name: Sign app APK
        uses: Tlaster/android-sign@v1.2.2
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          output: build/release/signed
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
          
      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1.0.7
        with:
          serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.kotlinquiz.app
          releaseFile: app/build/outputs/bundle/release/app-release.aab
          track: beta
          inAppUpdatePriority: 2
          userFraction: 0.33
          whatsNewDirectory: distribution/whatsnew
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
        
